// ems-frontend/src/components/EmployeeComponent.jsx
import React, { useState, useEffect } from "react";
import {
  createEmployee,
  getEmployee,
  updateEmployee,
} from "../services/EmployeeService";
import { useNavigate, useParams } from "react-router-dom";
import { getAllDepartments } from "../services/DepartmentService";

const EmployeeComponent = () => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [departments, setDepartments] = useState([]);

  useEffect(() => {
    getAllDepartments()
      .then((response) => {
        console.log("API RESPONSE:", response);
        console.log("DATA:", response.data);
        setDepartments(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  const { id } = useParams();
  const [errors, setErrors] = useState({
    firstName: "",
    lastName: "",
    email: "",
    department: "",
  });

  const navigator = useNavigate();

  useEffect(() => {
    if (id) {
      getEmployee(id)
        .then((response) => {
          setFirstName(response.data.firstName);
          setLastName(response.data.lastName);
          setEmail(response.data.email);
          setDepartmentId(response.data.departmentId);
        })
        .catch((error) => {
          console.error(error);
        });
    }
  }, [id]);

  function saveOrUpdateEmployee(e) {
    e.preventDefault();
    //  const isDuplicateEmail = employees.some(emp => emp.email === email && emp.id !== Number(id));
    if (validateForm()) {
      const employee = {
        firstName,
        lastName,
        email,
        departmentId: Number(departmentId), // ✅ FIX
      };
      console.log(employee);

      if (id && id !== "undefined") {
        updateEmployee(id, employee)
          .then((response) => {
            console.log(response.data);
            navigator("/employees");
          })
          .catch((error) => {
            console.error(error);
          });
      } else {
        createEmployee(employee)
          .then((response) => {
            console.log(response.data);
            navigator("/employees");
          })
          .catch((error) => {
            console.error(error);
          });
      }
    }
  }

  function validateForm() {
    let valid = true;

    const errorsCopy = { ...errors };

    if (firstName.trim()) {
      errorsCopy.firstName = "";
    } else {
      errorsCopy.firstName = "First name is required";
      valid = false;
    }

    if (lastName.trim()) {
      errorsCopy.lastName = "";
    } else {
      errorsCopy.lastName = "Last name is required";
      valid = false;
    }

    if (email.trim()) {
      errorsCopy.email = "";
    } else {
      errorsCopy.email = "Email is required";
      valid = false;
    }

    if (departmentId) {
      errorsCopy.department = "";
    } else {
      errorsCopy.department = "Select Department";
      valid = false;
    }

    setErrors(errorsCopy);

    return valid;
  }

  function pageTitle() {
    if (id) {
      return <h2 className="text-center">Update Employee</h2>;
    } else {
      return <h2 className="text-center">Add Employee</h2>;
    }
  }

  return (
    <div className="container">
      <br /> <br />
      <div className="row">
        <div className="card col-md-6 offset-md-3 offset-md-3">
          {pageTitle()}
          <div className="card-body">
            <form onSubmit={saveOrUpdateEmployee}>
              <div className="form-group mb-2">
                <label className="form-label">First Name:</label>
                <input
                  type="text"
                  placeholder="Enter Employee First Name"
                  name="firstName"
                  value={firstName}
                  className={`form-control ${errors.firstName ? "is-invalid" : ""}`}
                  onChange={(e) => setFirstName(e.target.value)}
                ></input>
                {errors.firstName && (
                  <div className="invalid-feedback"> {errors.firstName} </div>
                )}
              </div>

              <div className="form-group mb-2">
                <label className="form-label">Last Name:</label>
                <input
                  type="text"
                  placeholder="Enter Employee Last Name"
                  name="lastName"
                  value={lastName}
                  className={`form-control ${errors.lastName ? "is-invalid" : ""}`}
                  onChange={(e) => setLastName(e.target.value)}
                ></input>
                {errors.lastName && (
                  <div className="invalid-feedback"> {errors.lastName} </div>
                )}
              </div>

              <div className="form-group mb-2">
                <label className="form-label">Email:</label>
                <input
                  type="text"
                  placeholder="Enter Employee Email"
                  name="email"
                  value={email}
                  className={`form-control ${errors.email ? "is-invalid" : ""}`}
                  onChange={(e) => setEmail(e.target.value)}
                ></input>
                {errors.email && (
                  <div className="invalid-feedback"> {errors.email} </div>
                )}
              </div>

              <div className="form-group mb-2">
                <label className="form-label">Select Department:</label>
                <select
                  className={`form-control ${errors.department ? "is-invalid" : ""}`}
                  value={departmentId}
                  onChange={(e) => setDepartmentId(e.target.value)}
                >
                  <option value="">Select Department</option>
                  {departments.map((department) => (
                    <option key={department.id} value={department.id}>
                      {" "}
                      {department.departmentName}
                    </option>
                  ))}
                </select>
                {errors.department && (
                  <div className="invalid-feedback"> {errors.department} </div>
                )}
              </div>
              {/* <button className='btn btn-success' onClick={saveOrUpdateEmployee} >Submit</button> */}
              <button type="submit" className="btn btn-success mb-2">
                Submit
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmployeeComponent;

// ems-angular-frontend/src/app/components/employee/employee.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { EmployeeService } from '../../services/employee';
import { DepartmentService } from '../../services/department';
import { Employee as EmployeeModel } from '../../models/employee.model';
import { Department } from '../../models/department.model';

@Component({
  selector: 'app-employee',
  imports: [CommonModule, FormsModule],
  templateUrl: './employee.html',
  styleUrl: './employee.css',
})
export class Employee implements OnInit {
  id: number | null = null;
  firstName = '';
  lastName = '';
  email = '';
  departmentId: number | string = '';
  departments: Department[] = [];

  errors = {
    firstName: '',
    lastName: '',
    email: '',
    department: ''
  };

  constructor(
    private employeeService: EmployeeService,
    private departmentService: DepartmentService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.departmentService.getAllDepartments().subscribe({
      next: (data) => { this.departments = data; },
      error: (error) => { console.error(error); }
    });

    const paramId = this.route.snapshot.paramMap.get('id');
    if (paramId) {
      this.id = Number(paramId);
      this.employeeService.getEmployee(this.id).subscribe({
        next: (data) => {
          this.firstName = data.firstName;
          this.lastName = data.lastName;
          this.email = data.email;
          this.departmentId = data.departmentId;
        },
        error: (error) => { console.error(error); }
      });
    }
  }

  pageTitle(): string {
    return this.id ? 'Update Employee' : 'Add Employee';
  }

  validateForm(): boolean {
    let valid = true;
    this.errors = { firstName: '', lastName: '', email: '', department: '' };

    if (!this.firstName.trim()) { this.errors.firstName = 'First name is required'; valid = false; }
    if (!this.lastName.trim()) { this.errors.lastName = 'Last name is required'; valid = false; }
    if (!this.email.trim()) { this.errors.email = 'Email is required'; valid = false; }
    if (!this.departmentId) { this.errors.department = 'Select Department'; valid = false; }

    return valid;
  }

  saveOrUpdateEmployee(): void {
    if (!this.validateForm()) return;

    const employee: EmployeeModel = {
      firstName: this.firstName,
      lastName: this.lastName,
      email: this.email,
      departmentId: Number(this.departmentId)
    };

    if (this.id) {
      this.employeeService.updateEmployee(this.id, employee).subscribe({
        next: () => { this.router.navigate(['/employees']); },
        error: (error) => { console.error(error); }
      });
    } else {
      this.employeeService.createEmployee(employee).subscribe({
        next: () => { this.router.navigate(['/employees']); },
        error: (error) => { console.error(error); }
      });
    }
  }
}
